image: archlinux:base-devel
cache:
  key: system-v1
  paths:
    # For some reason Gitlab CI only supports storing cache/artifacts in a path relative to the build directory
    - .pkg-cache

test:
  stage: test
  before_script:
    - pacman -Syu --noconfirm --noprogressbar --cachedir .pkg-cache
      meson gcc gcovr gtest fmt
    - meson -Db_coverage=true -Dbuild_tests=true build
  script:
    - ninja -C build
    - ninja -C build test
    - ninja -C build coverage-text >/dev/null
    - ninja -C build coverage-xml >/dev/null
    - cp build/meson-logs/coverage.xml coverage.xml
    - ninja -C build show-coverage
  coverage: '/TOTAL.*\s+(\d+\%)/'
  artifacts:
    reports:
      cobertura: coverage.xml
