image: archlinux:base-devel
cache:
  key: system-v1
  paths:
    # For some reason Gitlab CI only supports storing cache/artifacts in a path relative to the build directory
    - .pkg-cache
stages:
  - build
  - test

lint:
  stage: .pre
  before_script:
    - pacman -Sy --noconfirm --noprogressbar --cachedir .pkg-cache
      archlinux-keyring
    - pacman -Syu --noconfirm --noprogressbar --cachedir .pkg-cache
      gcc gtest boost fmt clang python3
  script:
    - ./scripts/tidy.py

build:
  stage: build
  before_script:
    - pacman -Sy --noconfirm --noprogressbar --cachedir .pkg-cache
      archlinux-keyring
    - pacman -Syu --noconfirm --noprogressbar --cachedir .pkg-cache
      meson gcc boost fmt clang
    - meson build
  script:
    - ninja -C build

test:
  stage: test
  before_script:
    - pacman -Sy --noconfirm --noprogressbar --cachedir .pkg-cache
      archlinux-keyring
    - pacman -Syu --noconfirm --noprogressbar --cachedir .pkg-cache
      meson gcc gcovr gtest boost fmt clang
    - meson -Db_coverage=true -Dbuild_tests=true build
  script:
    - ninja -C build
    - ninja -C build test
    - ninja -C build cov
    - cp build/meson-logs/coverage.xml coverage.xml
  coverage: '/TOTAL.*\s+(\d+\%)/'
  artifacts:
    reports:
      cobertura: coverage.xml
